/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_lovedj_JniStudy */

#ifndef _Included_com_lovedj_JniStudy
#define _Included_com_lovedj_JniStudy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lovedj_JniStudy
 * Method:    getString2FromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lovedj_JniStudy_getString2FromC
  (JNIEnv *, jobject);

JNIEXPORT jstring JNICALL Java_com_lovedj_JniStudy_accessField
(JNIEnv *, jobject);

/*
 * Class:     com_lovedj_JniStudy
 * Method:    getStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lovedj_JniStudy_getStringFromC
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
